; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Demos:B/Bacteria/Bacteria.slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "B" "Bacteria - The Crusaders"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Demos:B/Bacteria/"
IF EXISTS ENV:whdloadargs
  whdload "Bacteria.slave" $whdloadargs
ELSE
  whdload "Bacteria.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
