; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Demos:B/BanditsRadio/BanditsRadio.Slave

; Favourites Mode
IF EXISTS ENV:favouritesmode
  execute S:AGS2Favourites "B" "Bandit's Radio - Mad elks"
  IF $favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Demos:B/BanditsRadio/"
IF EXISTS ENV:whdloadargs
  whdload "BanditsRadio.Slave" $whdloadargs
ELSE
  whdload "BanditsRadio.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
