; HstWB Menu Item Run script for AGS2
; -----------------------------------
;RunFile=A-Demos:T/ToxicZiemniak/ToxicZiemniak.Slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "T" "Toxic Ziemniak - Alchemy"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Demos:T/ToxicZiemniak/"
IF EXISTS ENV:whdloadargs
  whdload "ToxicZiemniak.Slave" $whdloadargs
ELSE
  whdload "ToxicZiemniak.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
