; AGS2 run script
; ---------------
;RunFile=A-Demos:P/PublicAttack/PublicAttack.slave

; Favourites Mode
IF EXISTS ENV:ags2favouritesmode
  execute S:AGS2Favourites "P" "Public Attack - Cult"
  IF $ags2favouritesmode EQ "add"
    SKIP end
  ENDIF
  IF $ags2favouritesmode EQ "remove"
    SKIP end
  ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Run WHDLoad
cd "A-Demos:P/PublicAttack/"
IF EXISTS ENV:whdloadargs
  whdload "PublicAttack.slave" $whdloadargs
ELSE
  whdload "PublicAttack.slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end
