; Favourites Mode
IF EXISTS ENV:favouritesmode
	execute S:Favourites "ags2" "T" "Toxic Ziemniak - Alchemy"
	IF $favouritesmode EQ "add"
		SKIP end
	ENDIF
	IF $favouritesmode EQ "remove"
		SKIP end
	ENDIF
ENDIF

; Start AGS2 Run Pre Script, if it exists
IF EXISTS S:AGS2RunPre
  execute S:AGS2RunPre
ENDIF

; Whdload
cd "A-Demos:T/ToxicZiemniak/"
IF EXISTS ENV:whdloadargs
	whdload "ToxicZiemniak.Slave" $whdloadargs
ELSE
	whdload "ToxicZiemniak.Slave"
ENDIF

; Start AGS2 Run Post Script, if it exists
IF EXISTS S:AGS2RunPost
  execute S:AGS2RunPost
ENDIF

; End
LAB end

